import { useCallback, useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { ImagePlus, Pencil, Plus, Trash2 } from "lucide-react";
import { api } from "../services/api";

const emptyProduct = {
  itemname: "",
  categoryID: "",
  itembaseprice: "",
  itemquantity: "",
  itemdescription: "",
};

function Notice({ error, success }) {
  if (!error && !success) return null;
  return <p role="alert" className={`mt-4 p-3 text-sm ${error ? "bg-red-50 text-red-800" : "bg-emerald-50 text-emerald-800"}`}>{error || success}</p>;
}

export function AdminProducts() {
  const [items, setItems] = useState([]);
  const [error, setError] = useState("");
  const load = useCallback(async () => {
    try { setItems(await api.getProducts()); } catch (err) { setError(err.message); }
  }, []);
  useEffect(() => { load(); }, [load]);
  const remove = async (item) => {
    if (!window.confirm(`Remove ${item.itemname}?`)) return;
    try { await api.deleteItem(item.itemID); await load(); } catch (err) { setError(err.message); }
  };
  return <>
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Catalog</p><h1 className="serif mt-2 text-4xl">Products</h1></div><div className="flex gap-3"><Link className="btn btn-light" to="/admin/categories"><Plus size={16}/> Add category</Link><Link className="btn btn-dark" to="/admin/items/new"><Plus size={16}/> Add product</Link></div></div>
    <Notice error={error} />
    <div className="mt-7 overflow-x-auto border border-stone-200 bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b text-stone-500"><tr><th className="p-4">Product</th><th className="p-4">Category</th><th className="p-4">Price</th><th className="p-4">Stock</th><th className="p-4">Actions</th></tr></thead><tbody>{items.map((item) => <tr className="border-b last:border-0" key={item.itemID}><td className="p-4"><div className="flex items-center gap-3">{item.primaryImage ? <img className="h-11 w-9 object-cover" src={item.primaryImage} alt="" /> : <div className="h-11 w-9 bg-stone-100"/>}<span className="font-medium">{item.itemname}</span></div></td><td className="p-4">{item.catgender} / {item.categorytype}</td><td className="p-4">${Number(item.itembaseprice).toFixed(2)}</td><td className="p-4">{item.itemquantity}</td><td className="p-4"><div className="flex gap-3"><Link className="underline" to={`/admin/items/${item.itemID}/edit`}><Pencil size={15}/><span className="sr-only">Edit</span></Link><button className="text-red-700" onClick={() => remove(item)} aria-label={`Remove ${item.itemname}`}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table>{!items.length && !error && <p className="p-8 text-center text-sm text-stone-500">No products yet. Add your first product.</p>}</div>
  </>;
}

export function AdminProductForm() {
  const { id } = useParams(); const nav = useNavigate(); const editing = Boolean(id);
  const [form, setForm] = useState(emptyProduct); const [categories, setCategories] = useState([]); const [image, setImage] = useState(null); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { (async () => { try { const categoryData = await api.getCategories(); setCategories(categoryData); if (editing) { const products = await api.getProducts(); const product = products.find((item) => String(item.itemID) === id); if (!product) throw new Error("Product not found"); setForm({ itemname: product.itemname, categoryID: String(product.categoryID), itembaseprice: product.itembaseprice, itemquantity: product.itemquantity, itemdescription: product.itemdescription || "" }); } } catch (err) { setError(err.message); } })(); }, [editing, id]);
  const submit = async (event) => { event.preventDefault(); setError(""); setSuccess(""); setSaving(true); try { const payload = { ...form, categoryID: Number(form.categoryID), itembaseprice: Number(form.itembaseprice), itemquantity: Number(form.itemquantity) }; const result = editing ? await api.updateItem(id, payload) : await api.createItem(payload); const itemID = editing ? id : result.item?.itemID; if (image) await api.uploadProductImage(itemID, image); setSuccess(editing ? "Product updated." : "Product added to the database."); if (!editing) setTimeout(() => nav("/admin/items"), 700); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  return <><p className="eyebrow">Catalog / stock listing</p><h1 className="serif mt-2 text-4xl">{editing ? "Edit clothing item" : "Upload new clothing item"}</h1><p className="mt-2 text-sm text-stone-500">Set the details that customers will see in the shop.</p><form onSubmit={submit} className="mt-7 max-w-3xl space-y-6 rounded-2xl border border-stone-200 bg-white p-7 shadow-sm"><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-medium">ITEM NAME<input required placeholder="e.g. Linen Overshirt" className="field mt-2" value={form.itemname} onChange={(e) => setForm({...form, itemname:e.target.value})}/></label><label className="block text-sm font-medium">CATEGORY<div className="mt-2 flex gap-2"><select required className="field min-w-0 flex-1" value={form.categoryID} onChange={(e) => setForm({...form, categoryID:e.target.value})}><option value="">Select category</option>{categories.map((category) => <option key={category.categoryID} value={category.categoryID}>{category.catgender} / {category.categorytype}</option>)}</select><Link className="btn btn-light shrink-0" to="/admin/categories">New</Link></div></label><label className="block text-sm font-medium">PRICE (USD)<input required min="0" step="0.01" type="number" placeholder="0.00" className="field mt-2" value={form.itembaseprice} onChange={(e) => setForm({...form, itembaseprice:e.target.value})}/></label><label className="block text-sm font-medium">AVAILABLE STOCK<input required min="0" step="1" type="number" placeholder="0" className="field mt-2" value={form.itemquantity} onChange={(e) => setForm({...form, itemquantity:e.target.value})}/></label></div><label className="block text-sm font-medium">DESCRIPTION<textarea placeholder="Describe the fabric, fit, colour, or styling..." className="field mt-2 min-h-32" maxLength="500" value={form.itemdescription} onChange={(e) => setForm({...form, itemdescription:e.target.value})}/></label><label className="flex min-h-30 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-stone-300 px-5 text-center transition hover:border-stone-900"><ImagePlus size={22}/><span className="mt-2 text-sm font-medium">{image ? image.name : "Choose a clothing image"}</span><span className="mt-1 text-xs text-stone-500">JPEG, PNG, WebP or GIF · maximum 5 MB</span><input className="sr-only" accept="image/jpeg,image/png,image/webp,image/gif" type="file" onChange={(e) => setImage(e.target.files?.[0] || null)}/></label><Notice error={error} success={success}/><div className="flex gap-3"><button disabled={saving} className="btn btn-dark flex-1">{saving ? "Saving..." : editing ? "Save clothing item" : "Publish clothing item"}</button><Link className="btn btn-light" to="/admin/items">Cancel</Link></div></form></>;
}

export function AdminCategories() {
  const [categories, setCategories] = useState([]); const [form, setForm] = useState({catgender:"", categorytype:""}); const [editing, setEditing] = useState(null); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const load = useCallback(async () => { try { setCategories(await api.getCategories()); } catch (err) { setError(err.message); } }, []); useEffect(() => { load(); }, [load]);
  const submit = async (event) => { event.preventDefault(); setError(""); setSuccess(""); try { if (editing) await api.updateCategory(editing, form); else await api.createCategory(form); setForm({catgender:"", categorytype:""}); setEditing(null); setSuccess(editing ? "Category updated." : "Category created."); await load(); } catch (err) { setError(err.message); } };
  const remove = async (category) => { if (!window.confirm(`Remove ${category.catgender} / ${category.categorytype}?`)) return; try { await api.deleteCategory(category.categoryID); await load(); } catch (err) { setError(err.message); } };
  return <><p className="eyebrow">Catalog</p><h1 className="serif mt-2 text-4xl">Categories</h1><div className="mt-7 grid gap-6 xl:grid-cols-[380px_1fr]"><form onSubmit={submit} className="h-fit space-y-4 border border-stone-200 bg-white p-6"><h2 className="serif text-2xl">{editing ? "Edit category" : "New category"}</h2><label className="block text-sm font-medium">Audience / gender<input required maxLength="10" className="field mt-2" placeholder="Women, Men, All" value={form.catgender} onChange={(e) => setForm({...form, catgender:e.target.value})}/></label><label className="block text-sm font-medium">Category name<input required maxLength="30" className="field mt-2" placeholder="Outerwear" value={form.categorytype} onChange={(e) => setForm({...form, categorytype:e.target.value})}/></label><Notice error={error} success={success}/><div className="flex gap-3"><button className="btn btn-dark">{editing ? "Save category" : "Add category"}</button>{editing && <button type="button" className="btn btn-light" onClick={() => {setEditing(null);setForm({catgender:"",categorytype:""});}}>Cancel</button>}</div></form><div className="overflow-x-auto border border-stone-200 bg-white"><table className="w-full min-w-[450px] text-left text-sm"><thead className="border-b text-stone-500"><tr><th className="p-4">Audience</th><th className="p-4">Category</th><th className="p-4">Actions</th></tr></thead><tbody>{categories.map((category) => <tr className="border-b last:border-0" key={category.categoryID}><td className="p-4">{category.catgender}</td><td className="p-4 font-medium">{category.categorytype}</td><td className="p-4"><div className="flex gap-3"><button className="underline" onClick={() => {setEditing(category.categoryID);setForm({catgender:category.catgender,categorytype:category.categorytype});}}><Pencil size={15}/></button><button className="text-red-700" onClick={() => remove(category)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table>{!categories.length && !error && <p className="p-8 text-center text-sm text-stone-500">No categories yet.</p>}</div></div></>;
}
